version: '3.7'
services:
  postgres:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_USER: postgres_test
      POSTGRES_DB: postgres_test
